# Generated by Django 2.0.2 on 2018-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='album',
            name='logo',
            field=models.FileField(default='music/static/music/images/fav star.jpg', upload_to=''),
        ),
    ]
