# Generated by Django 2.0.2 on 2018-03-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180224_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favorite',
        ),
    ]
