# Generated by Django 2.0.2 on 2018-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default='music/static/music/images/fav star.jpg', upload_to=''),
        ),
    ]
